# mapping_rule_id is generated by the server on creation, so it must be
# looked up (e.g. via the API or the Camunda Console) before it can be
# imported.
terraform import camundacluster_mapping_rule.admin "2251799813685251"
