package provider

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"

	camunda "github.com/camunda/terraform-provider-camunda-cluster/pkg/camunda/8.9"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &MappingRuleResource{}
var _ resource.ResourceWithImportState = &MappingRuleResource{}

func NewMappingRuleResource() resource.Resource {
	return &MappingRuleResource{}
}

// MappingRuleResource defines the resource implementation.
type MappingRuleResource struct {
	client *camunda.ClientWithResponses
}

// MappingRuleResourceModel describes the resource data model.
type MappingRuleResourceModel struct {
	ClaimName     types.String `tfsdk:"claim_name"`
	ClaimValue    types.String `tfsdk:"claim_value"`
	MappingRuleId types.String `tfsdk:"mapping_rule_id"`
	Name          types.String `tfsdk:"name"`
}

func (r *MappingRuleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mapping_rule"
}

func (r *MappingRuleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Camunda cluster mapping rule",

		Attributes: map[string]schema.Attribute{
			"claim_name": schema.StringAttribute{
				MarkdownDescription: "The name of the claim to map.",
				Required:            true,
			},
			"claim_value": schema.StringAttribute{
				MarkdownDescription: "The value of the claim to map.",
				Required:            true,
			},
			// mapping_rule_id is server-generated (unlike other identity resources, where the
			// caller supplies the unique ID), so it is Computed rather than Required, and doubles
			// as this resource's identifier.
			"mapping_rule_id": schema.StringAttribute{
				MarkdownDescription: "The unique ID of the mapping rule, generated by the server.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the mapping rule.",
				Required:            true,
			},
		},
	}
}

func (r *MappingRuleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*camunda.ClientWithResponses)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *camunda.ClientWithResponses, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *MappingRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data MappingRuleResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	request := camunda.CreateMappingRuleJSONRequestBody{
		ClaimName:  data.ClaimName.ValueString(),
		ClaimValue: data.ClaimValue.ValueString(),
		Name:       data.Name.ValueString(),
	}
	apiResp, err := r.client.CreateMappingRuleWithResponse(ctx, request)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create mapping rule, got error: %s", err))
		return
	}

	if apiResp.StatusCode() != http.StatusCreated {
		resp.Diagnostics.AddError("Not Created", fmt.Sprintf("Error while creating mapping rule, got HTTP error: %d: %s", apiResp.StatusCode(), apiResp.Body))
		return
	}

	mappingRuleId := apiResp.JSON201.MappingRuleId

	_, err = readMappingRuleWithRetry(ctx, r.client, mappingRuleId)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read mapping rule after creation, got error: %s", err))
		return
	}

	data.MappingRuleId = types.StringValue(apiResp.JSON201.MappingRuleId)
	data.ClaimName = types.StringValue(apiResp.JSON201.ClaimName)
	data.ClaimValue = types.StringValue(apiResp.JSON201.ClaimValue)
	data.Name = types.StringValue(apiResp.JSON201.Name)

	// Write logs using the tflog package
	// Documentation: https://terraform.io/plugin/log
	tflog.Trace(ctx, "created mapping rule resource")

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MappingRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data MappingRuleResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	apiResp, err := readMappingRuleWithRetry(ctx, r.client, data.MappingRuleId.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read mapping rule '%s', got error: %s", data.MappingRuleId.ValueString(), err))
		return
	}

	data.MappingRuleId = types.StringValue(apiResp.JSON200.MappingRuleId)
	data.ClaimName = types.StringValue(apiResp.JSON200.ClaimName)
	data.ClaimValue = types.StringValue(apiResp.JSON200.ClaimValue)
	data.Name = types.StringValue(apiResp.JSON200.Name)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MappingRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data MappingRuleResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	request := camunda.UpdateMappingRuleJSONRequestBody{
		ClaimName:  data.ClaimName.ValueString(),
		ClaimValue: data.ClaimValue.ValueString(),
		Name:       data.Name.ValueString(),
	}
	apiResp, err := r.client.UpdateMappingRuleWithResponse(ctx, data.MappingRuleId.ValueString(), request)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update mapping rule, got error: %s", err))
		return
	}

	if apiResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Not Updated", fmt.Sprintf("Error while updating mapping rule, got HTTP error: %d", apiResp.StatusCode()))
		return
	}

	data.MappingRuleId = types.StringValue(apiResp.JSON200.MappingRuleId)
	data.ClaimName = types.StringValue(apiResp.JSON200.ClaimName)
	data.ClaimValue = types.StringValue(apiResp.JSON200.ClaimValue)
	data.Name = types.StringValue(apiResp.JSON200.Name)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MappingRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data MappingRuleResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	apiResp, err := r.client.DeleteMappingRuleWithResponse(ctx, data.MappingRuleId.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete mapping rule, got error: %s", err))
		return
	}

	if apiResp.StatusCode() != http.StatusNoContent {
		resp.Diagnostics.AddError("Not Deleted", fmt.Sprintf("Error while deleting mapping rule, got HTTP error: %d", apiResp.StatusCode()))
		return
	}
}

func (r *MappingRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("mapping_rule_id"), req, resp)
}

// readMappingRuleWithRetry handles the eventual consistency of fetching a mapping rule by retrying a few times.
func readMappingRuleWithRetry(ctx context.Context, client *camunda.ClientWithResponses, mappingRuleId string) (*camunda.GetMappingRuleResponse, error) {
	// Reading a mapping rule is eventually consistent: if a mapping rule is just created, it may
	// not be immediately available through the API. Handle the eventual consistency by retrying a
	// few times with some delay in between until the mapping rule is found or we timeout.
	createState := &retry.StateChangeConf{
		Pending: []string{
			fmt.Sprintf("%d", http.StatusNotFound),
		},

		Target: []string{
			fmt.Sprintf("%d", http.StatusOK),
		},

		// How many times the target state has to be reached to continue.
		ContinuousTargetOccurence: 1,

		Refresh: func() (any, string, error) {
			readResp, err := client.GetMappingRuleWithResponse(ctx, mappingRuleId)

			if err != nil {
				return nil, "", err
			}

			return readResp, fmt.Sprintf("%d", readResp.StatusCode()), nil
		},

		// Don't wait too long for the first poll
		Delay:      1 * time.Second,
		MinTimeout: 2 * time.Second,
		// Wait at most this duration before considering the mapping rule has not been found
		Timeout: 30 * time.Second,
	}

	resp, err := createState.WaitForStateContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("timed out while waiting for mapping rule '%s' to be created: %w", mappingRuleId, err)
	}

	r, ok := resp.(*camunda.GetMappingRuleResponse)
	if !ok {
		// This should not happen
		return nil, fmt.Errorf("unexpected type for mapping rule read response: %T", resp)
	}

	return r, nil
}
